name: Build jdTweak

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build .deb
        run: |
          make clean package

      - name: Upload .deb to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: output/*.deb
          tag: v1.0
          token: ${{ secrets.API_TOKEN }}
          name: jdTweak v1.0
          body: "自动构建发布的京东 Quantumult X 插件"
